### ISSUE TITLE
Conversion from TestNG assertions should also be added to documentation

### ISSUE THREAD

**Issue by wimdeblauwe** [joel-costigliola/assertj#14]
Just like https://github.com/joel-costigliola/assertj/blob/gh-pages/assertj-core-converting-junit-assertions-to-assertj.html but then for TestNG

**Comment by joel-costigliola** [comment]
indeed.

**Comment by joel-costigliola** [comment]
http://joel-costigliola.github.io/assertj/assertj-core-converting-testng-assertions-to-assertj.html
