### ISSUE TITLE
"Converting TestNG Assertions to AssertJ" section no longer visible in right side menu

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj#59]
On http://joel-costigliola.github.io/assertj/assertj-core.html in the menu on the right side the "Converting TestNG Assertions to AssertJ" section is no longer visible (at least at 1920x1080 and below resolutions). There is no way to even scroll there, so the section seems to be unreachable.

**Comment by joel-costigliola** [comment]
This is what happens when a backend developer does front end stuff :smiley_cat: 

What would be the proper way to solve this ? add a scrollbar ?

**Comment by PascalSchumacher** [comment]
No sure what would be the best way to solve this.

Adding a scrollbar is an option, but maybe it's better to reorganize the menu a bit? E.g. merge the fest migration sections, move the converting sections to the migration section and remove the tools section because the only thing left in it will be the assertion generator section and that is already in the top menu.
