### ISSUE TITLE
Better android support documentation

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj#63]
We had many questions related to android support, ex: http://stackoverflow.com/questions/41787774/class-file-for-java-nio-file-path-not-found

**Comment by PascalSchumacher** [comment]
I'm closing this as we added: http://joel-costigliola.github.io/assertj/assertj-core.html#android for a start.

**Comment by joel-costigliola** [comment]
I wonder if it is worth to put an Android entry in the left menu, @PascalSchumacher  thoughts ?

**Comment by PascalSchumacher** [comment]
Sounds like a good idea.
