### ISSUE TITLE
Missing release notes for [3.0, 3.5)

### ISSUE THREAD

**Issue by TWiStErRob** [joel-costigliola/assertj#86]
http://joel-costigliola.github.io/assertj/assertj-core-news.html is back to 3.5.0
http://joel-costigliola.github.io/assertj/assertj-core-older-releases.html is up till 2.9.1
Where's are the notes for in between?

**Comment by PascalSchumacher** [comment]
They are also on https://joel-costigliola.github.io/assertj/assertj-core-older-releases.html below 2.9.1.

Releases form 3.1 to 3.9 were done in parallel with releases from 2.1 to 2.9 (3.x releases require Java 8, while 2.x releases require Java 7).

**Comment by joel-costigliola** [comment]
As @PascalSchumacher mentioned they have been moved to the older release page.

**Comment by TWiStErRob** [comment]
Oh boy, sorry! :)
I read the first 6 and the last 6 and they were in order, so assumed that the middle is too...
