### ISSUE TITLE
describe JUnit5 to AssertJ migration script

### ISSUE THREAD

**Issue by tomekkaczanowski** [joel-costigliola/assertj#89]
When https://github.com/joel-costigliola/assertj-core/issues/1350 is ready then we need to add info about Junit5 script to http://joel-costigliola.github.io/assertj/assertj-core-converting-junit-assertions-to-assertj.html

I will be happy to give it a try.

**Comment by joel-costigliola** [comment]
This is integrated thanks @tomekkaczanowski!
